# Generated by Django 4.1.7 on 2023-02-20 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='programs',
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.CharField(default=datetime.datetime(2023, 2, 20, 12, 1, 18, 561261, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='village',
            field=models.CharField(max_length=100),
        ),
    ]
