# Generated by Django 4.1.7 on 2023-02-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_student_enrollment_number_alter_student_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_number',
            field=models.IntegerField(default=0),
        ),
    ]
