# Generated by Django 4.1.6 on 2023-03-02 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_rename_name_student_first_name_student_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(default=datetime.datetime(2023, 3, 2, 5, 16, 28, 469995, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
