# Generated by Django 4.1.6 on 2023-03-29 04:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_rename_active_student_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default=datetime.datetime(2023, 3, 29, 4, 21, 19, 960674, tzinfo=datetime.timezone.utc), max_length=254, validators=[django.core.validators.RegexValidator(message='Enter a valid email address.', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default=datetime.datetime(2023, 3, 29, 4, 21, 33, 582858, tzinfo=datetime.timezone.utc), max_length=17, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
