# Generated by Django 4.1.5 on 2023-04-10 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_remove_programs_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_date', models.DateField()),
                ('allocation_time', models.TimeField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.programs')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.state')),
            ],
        ),
    ]
